apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    log.dirs=/var/lib/kafka/data
    zookeeper.connect=zookeeper:2181
    listeners=PLAINTEXT://0.0.0.0:9092
