apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j-config
data:
  log4j.properties: |
    # Content of log4j.properties here
    log4j.rootLogger=INFO, stdout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c - %m%n
