apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpesa-dashboard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: morganngetich/mpesa-frontend:latest  # ✅ Use built & pushed image
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: https://backend-ngetichmorgan6-dev.apps.openshift.com
