apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpesa-dashboard-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          volumeMounts:
            - name: kafka-config
              mountPath: /opt/kafka/config
          ports:
            - containerPort: 9092
          environment:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
      volumes:
        - name: kafka-config
          configMap:
            name: kafka-config
