apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ngetichmorgan6-dev
spec:
  containers:
    - name: test-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/data"
          name: uploads-volume
  volumes:
    - name: uploads-volume
      persistentVolumeClaim:
        claimName: uploads-pvc
