name: OpenShift CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/

      - name: Log in to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN --insecure-skip-tls-verify=true
          oc project ngetichmorgan6-dev  # Ensure correct OpenShift project is used

      - name: Get OpenShift Registry URL
        run: |
          echo "OPENSHIFT_REGISTRY=$(oc registry info)" >> $GITHUB_ENV

      - name: Build and Push Backend Image
        run: |
          docker build -t $OPENSHIFT_REGISTRY/ngetichmorgan6-dev/mpesa-dashboard-backend:latest ./mpesa-dashboard-backend
          docker login -u $(oc whoami) -p $(oc whoami -t) $OPENSHIFT_REGISTRY
          docker push $OPENSHIFT_REGISTRY/ngetichmorgan6-dev/mpesa-dashboard-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t $OPENSHIFT_REGISTRY/ngetichmorgan6-dev/mpesa-dashboard-frontend:latest ./mpesa-dashboard-frontend
          docker push $OPENSHIFT_REGISTRY/ngetichmorgan6-dev/mpesa-dashboard-frontend:latest

      - name: Deploy to OpenShift
        run: |
          oc apply -f k8s/  # Apply your OpenShift deployment configurations
          
      - name: Restart Deployments (Force Update)
        run: |
          oc rollout restart deployment/mpesa-dashboard-backend
          oc rollout restart deployment/mpesa-dashboard-frontend

      - name: Verify Deployment
        run: |
          oc get pods
          oc get services
          oc get routes
